[package]
name = "mp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.15.1" }
axum = "0.8.8"
clap = { version = "4.5.53", features = ["derive"] }
mime_guess = "2.0.5"
rand = "0.9.2"
rust-embed = "8.9.0"
tokio = { version = "1.48.0", features = ["full"] }